services:
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 15

  app:
    image: node-redis-counter:test
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PORT: "${APP_PORT:-3000}"
      REDIS_URL: "redis://redis:${REDIS_PORT:-6379}"
      COUNTER_KEY: "itest:hits"
      SERVICE_NAME: "node-redis-counter-itest"
      # (Optionnel côté app) SERVICE_VERSION si tu veux l'afficher :
      SERVICE_VERSION: "${SERVICE_VERSION:-1.0.0}"
    ports:
      - "${HOST_HTTP_PORT:-18080}:${APP_PORT:-3000}"
