version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 15

  app:
    image: node-redis-counter:test
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PORT: "3000"
      REDIS_URL: "redis://redis:6379"
      COUNTER_KEY: "itest:hits"
      SERVICE_NAME: "node-redis-counter-itest"
    ports:
      - "8080:3000"
